--Sample printers
insert into PRINTERS VALUES ('UUID-sample-1', 'MT2 6P DRUKARKA NEUTRON5K', 'ACTIVE', CURRENT_TIMESTAMP);
insert into PRINTERS VALUES ('UUID-sample-2', 'BG 1P DRUKARKA SZWAGRODRUK MEGATRON', 'ACTIVE', CURRENT_TIMESTAMP);
